
# cc_library(
#     name = "rgd",
#     srcs = ["rgd.cc"],
#     hdrs = [
#         "manifold.h",
#         "rgd.h",
#         "so3_cost_function_interface.h",
#         "rgd_cost_function_interface.h",
#         "gradient_checker.h"
#     ],
#     deps = ["@eigen//:eigen"],
#     visibility = ["//visibility:public"],
#     )

# cc_test(
#     name = "rgd_test",
#     srcs = ["rgd_test.cc"],
#     deps = [
#         ":rgd",
#         "@googletest//:gtest_main",
#         "@ceres//:ceres",
#     ]
# )
