
cc_library(
    name = "graph",
    srcs = ["graph.cc", "graph_normal_cut.cc"],
    hdrs = ["graph_normal_cut.h", "graph.h"],
    deps = ["@com_gitlab_libeigen_eigen//:eigen"],
    visibility = ["//visibility:public"],
    )