
cc_library(
    name = "algebra_operation",
    srcs = [
        "algebra_operation.cc",
    ],
    hdrs = [
        "algebra_operation.h",
    ],
    deps = [
	     "@eigen//:eigen",
         "@openblas//:openblas",
    ],
    visibility = ["//visibility:public"],
)