load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "algebra_operation",
    srcs = [
        "algebra_operation.cc",
    ],
    hdrs = [
        "algebra_operation.h",
    ],
    deps = [
	     "@eigen//:eigen",
    ],
    visibility = ["//visibility:public"],
)