name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libopenblas-dev \
          liblapack-dev \
          libeigen3-dev \
          libsuitesparse-dev \
          build-essential \
          cmake \
          pkg-config \
          wget
    - name: Download bazel
      run: wget https://github.com/bazelbuild/bazel/releases/download/7.4.1/bazel-7.4.1-linux-x86_64  && sudo chmod +x bazel-7.4.1-linux-x86_64
    - name: Info
      run: |
        ls
        ./bazel-7.4.1-linux-x86_64 --version
        pkg-config --modversion openblas
        pkg-config --modversion lapack
    - name: Unit Test
      run: ./bazel-7.4.1-linux-x86_64 test ...

