name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Download bazel
      run: wget https://github.com/bazelbuild/bazel/releases/download/7.4.1/bazel_7.4.1-linux-x86_64.deb && sudo dpkg -i bazel_7.4.1-linux-x86_64.deb
    - name: Unit Test
      run: bazel test ...

