name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Download bazel
      run: wget https://github.com/bazelbuild/bazel/releases/download/7.4.1/bazel-7.4.1-linux-x86_64  && sudo chmod +x bazel-7.4.1-linux-x86_64
    - name: Info
      run: ls && bazel --version
    - name: Unit Test
      run: ./bazel-7.4.1-linux-x86_64 test ...

