name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Eigen3
      uses: kupns-aka-kupa/setup-eigen3@v1
      
    - name: Googletest installer
      uses: MarkusJx/googletest-installer@v1.1
      
    - name: cmake configuration
      run: mkdir -p build && cd build && cmake ..
    - name: make check
      run: cd build && make

