name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libopenblas-dev \
          liblapack-dev \
          libsuitesparse-dev \
          build-essential \
          pkg-config \
          wget \
          gfortran \
          libgfortran5
    - name: Download bazelisk
      run: |
        wget -O bazelisk https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
        chmod +x bazelisk
    - name: Info
      run: |
        ls
        ./bazelisk --version
        pkg-config --modversion openblas
        pkg-config --modversion lapack
    - name: Unit Test
      run: ./bazelisk test ... --test_output=errors

